name: Commit Review

on:
  push:
    branches: "**"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          # for commit in ${{ github.event.commits }}; do
          #   echo ${commit[id]}
          # done
          for commit in $(git rev-list ${{ github.event.before}}..${{ github.event.after}}); do
              echo "run check for $commit"
          done
