name: Commit Review

on:
  push:
    branches: '**'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          for commit in ${{ github.event.commits }}; do
            echo $commit
          done
          # for commit in $(${{ github.event.before}}..${{ github.sha}}); do
          #     echo "run check for $commit"
          # done
