name: Commit Review Cleanup

on:
  pull_request_review:
    types: [submitted]
    branches:
      - "commit-review-**"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - run: |
          PR_URL="/repos/${{ github.repository }}/pulls/${{ github.event.pull_request_number }}"
          REMAINING=$(gh api "$PR_URL/requested_reviewers" | jq 'length')

          echo "Remaining Reviewers: $REMAINING"
          if [[ $REMAINING -eq 0 ]]; then
            BRANCHES=$(gh api --method PATCH $PR_URL -f state='closed' | jq '.base.ref,.head.ref')
            echo "Cleaning up branches ${BRANCHES[@]}"

            for BRANCH in ${BRANCHES[@]}; do
              git push origin --delete $BRANCH
            done
          fi
