name: Commit Review Cleanup

# TODO: does not get trigger for some reason
on:
  pull_request_review:
    types: [submitted]
    branches:
      - "commit-review-**"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo ${{github.event}}
          PR_URL="/repos/${{ github.repository }}/pulls/${{ github.event.number }}"
          REMAINING=$(gh api "$PR_URL/requested_reviewers" | jq 'length')

          if $REMAINING -eq 0; then
            BRANCHES=$(gh api --method PATCH $PR_URL -f state='closed' | jq '.base.ref,.head.ref')

            for BRANCH in ${BRANCHES[@]}; do
              git push origin --delete $BRANCH
            done
          fi
